"""Domain-owned rules behind the shared orchestration boundary."""
from typing import Protocol
from pydantic import BaseModel, ConfigDict, Field
from ..models import SceneState, Instruction

class DomainMetadata(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")
    domain_id: str = Field(pattern=r"^[a-z][a-z0-9_]*$")
    version: str = Field(min_length=1)
    display_name: str = Field(min_length=1)

class DomainPack(Protocol):
    metadata: DomainMetadata
    def opening(self, state: SceneState) -> Instruction: ...
    def recovery(self, state: SceneState) -> Instruction: ...
    def preempt(self, state: SceneState, text: str) -> Instruction | None: ...
    def guard(self, state: SceneState, text: str) -> Instruction | None: ...
    def paused(self, state: SceneState, text: str) -> Instruction: ...
    def silence(self, state: SceneState) -> Instruction: ...
    def is_cleared(self, state: SceneState) -> bool: ...
    def next_instruction(self, state: SceneState) -> Instruction: ...
